"""create project technologies table

Revision ID: 261fea5cb716
Revises: 82bd3537edfe
Create Date: 2026-09-10 11:07:42.810041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261fea5cb716'
down_revision: Union[str, Sequence[str], None] = '82bd3537edfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_technologies_id'), 'project_technologies', ['id'], unique=False)
    op.create_index(op.f('ix_project_technologies_project_id'), 'project_technologies', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_technologies_slug'), 'project_technologies', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_technologies_slug'), table_name='project_technologies')
    op.drop_index(op.f('ix_project_technologies_project_id'), table_name='project_technologies')
    op.drop_index(op.f('ix_project_technologies_id'), table_name='project_technologies')
    op.drop_table('project_technologies')
    # ### end Alembic commands ###
