"""create portfolio sections table

Revision ID: cd1ba8195319
Revises: 8ffc80bd2ec5
Create Date: 2026-09-08 11:51:14.952524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1ba8195319'
down_revision: Union[str, Sequence[str], None] = '8ffc80bd2ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_sections_id'), 'portfolio_sections', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_sections_portfolio_id'), 'portfolio_sections', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_sections_slug'), 'portfolio_sections', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_sections_slug'), table_name='portfolio_sections')
    op.drop_index(op.f('ix_portfolio_sections_portfolio_id'), table_name='portfolio_sections')
    op.drop_index(op.f('ix_portfolio_sections_id'), table_name='portfolio_sections')
    op.drop_table('portfolio_sections')
    # ### end Alembic commands ###
